"""Editing of masks, or replacement of automasks by edited masks"""

import os
import logging

from tqdm import tqdm
import numpy as np
import dbdicom as db
from miblab import pipe

from utils import data, edit


PIPELINE = 'rsfseg'

# Same class map used in stage_1_segment / stage_2_display / stage_3_measure.
RSF_CLASS_MAP = {
    1: 'left_kidney_sinus_fat',
    2: 'right_kidney_sinus_fat',
}

# Which mask series (produced in stage 1) can be edited. Add 'rsf_masks_2'
# here too if you also want to edit masks from the second method.
TASKS = ['rsf_masks']


def run(build, logfile, plane='coronal'):
    DIXON = r"X:\abdominal_imaging\Shared\Benthe"

    datapath = os.path.join(DIXON, 'dixon', 'stage_5_clean_dixon_data')
    maskpath = os.path.join(build, 'rsfseg', 'stage_1_segment')
    editpath = os.path.join(build, 'rsfseg', 'stage_4_edit')

    # Controls
    group = "Controls"
    sitedatapath = os.path.join(datapath, group)
    sitemaskpath = os.path.join(maskpath, group)
    siteeditpath = os.path.join(editpath, group)

    for task in TASKS:
        run_site(sitedatapath, sitemaskpath, siteeditpath, task, plane)

    group = "Patients"
    for site in ['Exeter', 'Bari', 'Leeds', 'Bordeaux', 'Turku', 'Sheffield']:
        sitedatapath = os.path.join(datapath, group, site)
        sitemaskpath = os.path.join(maskpath, group, site)
        siteeditpath = os.path.join(editpath, group, site)

        for task in TASKS:
            run_site(sitedatapath, sitemaskpath, siteeditpath, task, plane)


def run_site(sitedatapath, sitemaskpath, siteeditpath, task, plane):

    # Separate output folder per task, e.g. stage_4_edit/Controls/rsf_masks
    siteeditpath = os.path.join(siteeditpath, task)
    os.makedirs(siteeditpath, exist_ok=True)

    # List of selected dixon series
    record = data.dixon_record()
    all_dixon_series = db.series(sitedatapath)

    # Loop over the autogenerated masks
    for mask_series in tqdm(db.series(sitemaskpath)):

        # Skip if not the correct task (i.e. not this mask series, e.g. 'rsf_masks')
        if mask_series[3][0] != task:
            continue

        # Patient and output study
        patient = mask_series[1]
        study = mask_series[2][0]

        # Skip if the edited masks already exist
        edited_mask_study = [siteeditpath, patient, (study, 0)]
        edited_mask_series = edited_mask_study + [(f"{task}_edited", 0)]
        if edited_mask_series in db.series(edited_mask_study):
            continue

        # Get the fat sequence
        sequence = data.dixon_series_desc(record, patient, study)
        series_fat = [sitedatapath, patient, mask_series[2], (f'{sequence}_fat', 0)]

        # Skip if the Dixon fat series doesn't exist
        if series_fat not in all_dixon_series:
            logging.info(f"{patient} {study}: fat series not found, skipping.")
            continue

        try:
            fat = db.volume(series_fat)

            # Get the auto-mask (same study, same series description as `task`)
            auto_label_series = [sitemaskpath, patient, mask_series[2], (task, 0)]
            auto_label = db.volume(auto_label_series)
        except Exception as e:
            logging.error(f"{patient} {study} error reading data: {e}")
            continue

        # Round mask values before using as labels: after a DICOM write/read
        # round-trip, values that should be exactly 1 or 2 can come back as
        # e.g. 0.9998 or 2.0003 due to rescale slope/intercept quantization.
        auto_label_arr = np.round(auto_label.values).astype(np.int16)

        # Edit the mask and save
        transp = {
            'coronal': (0, 1, 2),
            'sagittal': (2, 1, 0),
            'axial': (0, 2, 1),
        }[plane]
        try:
            fatarr = fat.values.transpose(transp)
            lblarr = auto_label_arr.transpose(transp)
            # Both RSF labels (left=1, right=2) are edited together in the
            # same napari session; default_label just sets the initially
            # selected paint label, which can be changed within napari.
            edited_label = edit.edit_mask_with_napari(fatarr, lblarr, default_label=1)
            edited_label = edited_label.transpose(transp)
        except Exception as e:
            logging.error(f"{patient} {study} error editing mask: {e}")
        else:
            vol = (edited_label.astype(np.int16), fat.affine)
            db.write_volume(vol, edited_mask_series, ref=series_fat)
            # if not np.array_equal(auto_label_arr, vol[0]):
            #   db.write_volume(vol, edited_mask_series, ref=series_fat)


if __name__ == '__main__':

    BUILD = r"X:\abdominal_imaging\Shared\Benthe\iBEAt_Build"
    kwargs = {
        "plane": {
            'type': str,
            'default': 'coronal',
            'help': 'Plane',
        }
    }
    pipe.run_stage(run, BUILD, PIPELINE, __file__, **kwargs)